"use strict";

export default {
  BAD_REQUEST: "The request cannot be fulfilled due to bad syntax",
  OK: "Operation is successfully executed",
  CREATE_FAILED: "The request has not been fulfilled, Please try again",
  EMAIL_REGISTERED: "Email already registered.",
  MOBILE_REGISTERED: "Mobile already registered.",
  USERNAME_REGISTERED: "Username already registered.",
  USER_REGISTERED: "User registered successfully.",
  USER_REGISTER_FAILED: "Failed to registered user.",
  SERVER_ERROR: "Something bad happened on the server",
  LOGIN: "Successfully login.",
  EMAIL_DOB_IS_REQUIRED: "Email and date of birth is required to sign up.",
  EMAIL_ID_REQUIRED: "Email is required to sign up.",
  DOB_IS_REQUIRED: "Date of birth is required to sign up.",
  USER_LIST_NOT_FOUND: "User not found.",
  ERROR_SIGNING_TOKEN: "Can't sign token",
  AUTH_SUCCESS: "Authentication Successful",
  INVALID_PASSWORD: "Your password seems to be incorrect.",
  IN_EMAIL_PASSWORD: "Your Email or Password seems to be incorrect.",
  OTP_EXPIRE: "Your OTP has expires.",
  INVALID_OTP: "Invalid OTP.",
  RESET_PASSWORD_LINK: "We just shot you an email, take a look!",
  RESET_PASSWORD_LINK_EXPIRE: "Your reset password link is expired on invalid",
  CURRENT_PASSWORD_WRONG: "Current password you have entered is wrong.",
  USER_PASSWORD_RESET: "Password reset successfully.",
  MOBILE_NUMBER_NOT_VERIFIED:
    "Your mobile numbers is not verified. Please verify it before login.",
  PLAYERID_DUPLICATE: "Player id already exists.",
  PLAYERID_SAVED: "Player Id saved successfully.",
};
